# Generated by Django 5.0.6 on 2024-10-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisanApp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
