# Generated by Django 5.0.6 on 2024-10-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisanApp', '0004_remove_product_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
